### ISSUE TITLE
OR Operation 

### ISSUE THREAD

**Issue by kundansonuj** [RedisLabsModules/rebloom#20]
Hi,
Is OR Operation of two bloomfilters or merge of two bloomfilters possible?

**Comment by dvirsky** [comment]
Hi @kundansonuj. It's not possible to merge bloom filters, even if the filter parameters are equal, you would lose precision and end up with lots of false positives. The best way to "merge" is to check multiple filters for the same key. A command to do that would actually be a nice touch, although it's achievable with a MULTI transaction or with a Lua script.

**Comment by kundansonuj** [comment]
Hi @dvirsky ,
Thanks for the info, but why there would be loss in precision if i try to merge two bloomfilters with same parameters using bitwise OR.

**Comment by mnunberg** [comment]
@kundansonuj Because in order for the filters to be effective, they need to be at or below a certain fill rate. Every element has a certain number of bits which relate to it. A bloom filter works due to the probability that if *all* the element's bits are full, it is likely in the filter.

If you oversaturate a filter with bits, then you increase the probability that any given bit pattern will be nonzero

**Comment by itamarhaber** [comment]
Merging makes sense to me - you can parallelize building the filter by using an overprovisioned but identically-dimensioned BFs on all instances (each ending below saturation), and then merge them to one biggie for querying.

**Comment by mnunberg** [comment]
But what are you gaining then by merging? Just unifying under the same key?

**Comment by itamarhaber** [comment]
One key and one lookup I would presume.

**Comment by kundansonuj** [comment]
@itamarhaber , exactly my case. I will have multiple bloomfilters, but i want to unify a set of them under one oversized bloomfilter for single lookup

**Comment by dvirsky** [comment]
It just won't work reliably. Even internally when we need to grow a filter's capacity, we create new filters and look in multiple ones.
